### ISSUE TITLE
Hemiandrus jacinda

### ISSUE THREAD

**Issue by kcopas** [mdoering/famous-organism#20]
Newly described New Zealand cricket named for current PM—see [The Guardian](https://www.theguardian.com/world/2021/mar/12/hemiandrus-jacinda-insect-named-after-new-zealand-prime-minister-ardern) via [Zootaxa](https://doi.org/10.11646/zootaxa.4942.2.4)

**Comment by mdoering** [comment]
https://github.com/mdoering/famous-organism/commit/6fbcef0f7292a7d9c52215361143bdbf1e20622b
