### ISSUE TITLE
eml.xml referenced in meta.xml, but not included in archive

### ISSUE THREAD

**Issue by jhpoelen** [mdoering/famous-organism#25]
As I was chasing down bunnies (Sylvilagus floridanus) as part of a ongoing discussion at https://discourse.gbif.org/t/when-does-evidence-of-impact-become-too-onerous-to-track/4639/11, I stumbled across a darwin core archive with content id zip:hash://sha256/9eb81e2d2c5857b80ddbd3043b4706464b6d6223dc780369d6e093c43c4bf7e9!/famous-organism-master/eml.xml that was found in an Oct 2024 copy of GBIF/iDigBio registered datasets with id hash://sha256/fc6a81d2968272005c947df326ac3e99fd4db9b585198d64208c52475e9c1dc8 with a meta.xml containing:

```bash
preston cat 'zip:hash://sha256/9eb81e2d2c5857b80ddbd3043b4706464b6d6223dc780369d6e093c43c4bf7e9!/famous-organism-master/meta.xml'
```

with content

```
<archive xmlns="http://rs.tdwg.org/dwc/text/" metadata="eml.xml">
  <core encoding="utf-8" fieldsTerminatedBy="\t" linesTerminatedBy="\n" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Taxon">
    <files>
      <location>famous.tsv</location>
    </files>
    <id index="0" />
    <field index="0" term="http://rs.tdwg.org/dwc/terms/taxonID" />
    <field index="1" term="http://rs.tdwg.org/dwc/terms/acceptedNameUsageID" />
    <field index="2" term="http://rs.tdwg.org/dwc/terms/originalNameUsageID" />
    <field index="3" term="http://rs.tdwg.org/dwc/terms/taxonRank" />
    <field index="4" term="http://rs.tdwg.org/dwc/terms/taxonRemarks"/>
    <field index="6" term="http://rs.tdwg.org/dwc/terms/scientificName" />
    <field index="7" term="http://rs.tdwg.org/dwc/terms/scientificNameAuthorship"/>
    <field index="8" term="http://rs.tdwg.org/dwc/terms/namePublishedInYear" />
    <field index="9" term="http://rs.tdwg.org/dwc/terms/namePublishedIn"/>
    <field index="10" term="http://rs.tdwg.org/dwc/terms/namePublishedInID"/>
    <field index="12" term="http://rs.tdwg.org/dwc/terms/kingdom"/>
    <field index="13" term="http://rs.tdwg.org/dwc/terms/phylum"/>
    <field index="14" term="http://rs.tdwg.org/dwc/terms/class"/>
    <field index="15" term="http://rs.tdwg.org/dwc/terms/order"/>
    <field index="16" term="http://rs.tdwg.org/dwc/terms/family"/>
    <field index="17" term="http://purl.org/dc/terms/references"/>
  </core>
  <extension encoding="utf-8" fieldsTerminatedBy=";" linesTerminatedBy="\n" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.gbif.org/terms/1.0/SpeciesProfile">
      <files>
          <location>famous.tsv</location>
      </files>
      <coreid index="0" />
      <field index="11" term="http://rs.gbif.org/terms/1.0/isExtinct"/>
  </extension>
  <extension encoding="utf-8" fieldsTerminatedBy=";" linesTerminatedBy="\n" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.gbif.org/terms/1.0/VernacularName">
      <files>
          <location>famous.tsv</location>
      </files>
      <coreid index="0" />
      <field index="5" term="http://rs.tdwg.org/dwc/terms/vernacularName"/>
      <field default="eng" term="http://purl.org/dc/terms/language"/>
  </extension>
  <extension encoding="utf-8" fieldsTerminatedBy=";" linesTerminatedBy="\n" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.gbif.org/terms/1.0/Multimedia">
      <files>
          <location>famous.tsv</location>
      </files>
      <coreid index="0" />
      <field index="18" term="http://purl.org/dc/terms/identifier"/>
      <field index="19" term="http://purl.org/dc/terms/license"/>
      <field index="20" term="http://purl.org/dc/terms/creator"/>
      <field index="21" term="http://purl.org/dc/terms/references"/>
      <field default="StillImage" term="http://purl.org/dc/terms/type"/>
  </extension>
</archive>
```

Note that a ```metadata="eml.xml"``` was referenced, but no such file was found in the registered dwca . 

@mdoering any reason why you've reference the ```eml.xml``` but not included them in your neat https://github.com/mdoering/famous-organism ?

**Comment by jhpoelen** [comment]
Note that the associated content is:

```
preston cat 'hash://sha256/9eb81e2d2c5857b80ddbd3043b4706464b6d6223dc780369d6e093c43c4bf7e9' > bla.zip
unzip -l bla.zip 
Archive:  bla.zip
24fcd76c70d1a55c99021d252dcd4e6a1e6c3707
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2024-06-26 13:26   famous-organism-master/
       21  2024-06-26 13:26   famous-organism-master/.gitignore
      565  2024-06-26 13:26   famous-organism-master/README.md
      167  2024-06-26 13:26   famous-organism-master/lookup.sh
     2910  2024-06-26 13:26   famous-organism-master/meta.xml
     1176  2024-06-26 13:26   famous-organism-master/metadata.yaml
    22198  2024-06-26 13:26   famous-organism-master/name_usage.tsv
      235  2024-06-26 13:26   famous-organism-master/pre-commit.hook
    40011  2024-06-26 13:26   famous-organism-master/reference.bib
---------                     -------
    67283                     9 files
```

**Comment by jhpoelen** [comment]
found while doing down a rabbit hole at https://github.com/jhpoelen/cite-the-bunnies/issues/3 .

**Comment by mdoering** [comment]
> @mdoering any reason why you've reference the `eml.xml` but not included them in your neat https://github.com/mdoering/famous-organism ?

That must have been a leftover from switching from DwC-A to ColDP. `metadata.yaml` is now the source of truth and I have changed the meta.xml to reflect that.

**Comment by jhpoelen** [comment]
@mdoering thanks for  your prompt reply and fix.

To me, the metadata.yaml is much easier to read than the eml.xml. Yay for human readability!

Just curious - is the metadata.yaml following the EML standard. If not, can you point to some schema I can use so I can build in support for extracting some citation from the metadata.yaml ?

**Comment by mdoering** [comment]
the metadata.yaml is sth we developed as part of ColDP:
https://github.com/CatalogueOfLife/coldp/blob/master/README.md#metadata

It started with my long time disappointment that we have such a complex xml format for simple and essential metadata.
I then compared EML, DC, DataCite and a few other standards to extract what we thought of as the most important elements for checklist data. There is a conversion build into the CLB API and UI:

https://www.checklistbank.org/tools/metadata-generator

http://api.checklistbank.org/dataset/1199.yaml
http://api.checklistbank.org/dataset/1199.xml
http://api.checklistbank.org/dataset/1199.json

**Comment by mdoering** [comment]
here is the json schema: https://github.com/CatalogueOfLife/coldp/blob/master/metadata.json

**Comment by jhpoelen** [comment]
Neat! Thanks for making it easier to add metadata.
